<?php

/**
 * @file
 * Contains calendar_widget_d8.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function calendar_widget_d8_help($route_name, RouteMatchInterface $route_match) {
    switch ($route_name) {
        // Main module help for the calendar_widget_d8 module.
        case 'help.page.calendar_widget_d8':
            $output = '';
            $output .= '<h3>' . t('About') . '</h3>';
            $output .= '<p>' . t('Generates Calendar Displays of events from calendar.byu.edu for specific dates and categories.') . '</p>';
            return $output;

        default:
    }
}

/**
 * Implements hook_theme().
 */
function calendar_widget_d8_theme() {
    return [
        'calendar_widget_d8' => [
            'render element' => 'children',
        ],
    ];
}
